### ISSUE TITLE
Is there any check on CPU2?

### ISSUE THREAD

**Issue by FAAAAT** [jdmallen/dell-ipmi-fan-control-monitor#1]
Hello jdmallen,

I found there is only one temp regex item in configuration.

So is there any temp check on another cpu?

**Comment by jdmallen** [comment]
Hey there, good question. I'll take a glance when I get home. I'm not sure which one I'm polling, or if it's an average (if that was a reported value from ipmi), but if it's only one of them, I'll add an option to check the other with separate RegEx. Thanks for the catch!

**Comment by FAAAAT** [comment]
Hello jdmallen,

I checked the code and I think it just take the latest regex match as current temperature.

I have made a small change for it to return the max value of those two temp.

By the way, thanks for the great project.  It saved my ears and brain.. : )

**Comment by jdmallen** [comment]
Thanks for the PR! I'm glad you like the project and that others are getting use out of it.

I merged your PR and made some additional tweaks. I'll make a new release tomorrow after I get it installed on my rack and ensure it doesn't blow up.
